server:
  servlet:
    context-path: /api
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: AIRBD-API
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.15.76:3306/airboard?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wangzong666.
  jpa:
    show-sql: true
    hibernate:
      naming:
        #hibernate5.1版本后配置方式
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 5
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

####mybatis配置####
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.airboard.core.model

logging:
  config: classpath:logback-spring.xml
  path: D:/AIRBD-LOG/api-log