server:
  servlet:
    context-path:
  port: 80

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/static/,classpath:/static/,classpath:/resources/templates/,classpath:/templates/
  freemarker:
    suffix: .html  #\u540E\u7F00\u540D\uFF0C\u9ED8\u8BA4\u662F.ftl
    content-type: text/html
    enabled: true
    cache: false #\u7F13\u5B58\u914D\u7F6E
    template-loader-path: classpath:/templates/
    charset: UTF-8 #\u7F16\u7801\u683C\u5F0F
    request-context-attribute: ctx #\u8BF7\u6C42\uFF0C\u7C7B\u4F3Cjsp\u4E2D\u7684\u5185\u7F6E\u5BF9\u8C61