server:
  servlet:
    context-path: /asyn
  port: 8091

spring:
  application:
    name: AIRBD-ASYN
  rabbitmq:
    host: 47.106.15.76
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.106.15.76:8761/eureka/

logging:
  config: classpath:config/logback-spring.xml
  path: D:/logs/
  file: airbd-api.log
  level:
    root: info

rabbitmq:
  queue