server:
  servlet:
    context-path: /web
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.106.15.76:8761/eureka/

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.airboard.core.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 4
    logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

spring:
  application:
    name: AIRBD-WEB
  banner:
    location: /config/banner.txt
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/static/,classpath:/static/,classpath:/resources/templates/,classpath:/templates/
  freemarker:
    suffix: .html  #后缀名，默认是.ftl
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/
    charset: UTF-8 #编码格式
    request-context-attribute: ctx #请求，类似jsp中的内置对象
  datasource:
    druid:
      db1:
        username: root
        password: Wangzong666.
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.106.15.76:3306/airboard?useUnicode=true&characterEncoding=utf-8&useSSL=false
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        username: root
        password: Wangzong666.
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.106.15.76:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        initialSize: 5
        minIdle: 5
        maxActive: 20
  jpa:
    show-sql: true
    hibernate:
      naming:
        #hibernate5.1版本后配置方式
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1d
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最大空闲
        max-idle: 5
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

logging:
  config: classpath:config/logback-spring.xml
  path: D:/logs/
  file: airbd-web.log
  level:
    root: info

#shiro缓存前缀
shiro:
  cache:
    cache-prefix: shiro-redis-cache:
    #shiro缓存在redis过期时间是(分钟)
    cache-time: 180